import type { Region } from './types'

export const GALAXY_REGIONS: Region[] = [
  {
    id: 'premier-league',
    name: 'Premier League',
    country: 'England',
    color: '#3d195b',
    entryLore:
      'You step into the fog of North London, where the roar of 60,000 voices shakes the old concrete. The Premier League is not just a competition — it is a season-long war of attrition, where heroes fall and underdogs rise. Every matchday rewrites history.',
    completionLore:
      'You have walked every ground in England\'s top flight. The chants still echo in your memory. The Premier League left its mark on you — and on the galaxy.',
    milestones: [
      {
        nodesAtMinLevel: 2,
        minLevel: 1,
        title: 'First Steps in England',
        description: 'You have unlocked your first nodes in the Premier League.',
        bonusLabel: '+10% XP in Premier League',
        lore: 'The turnstile clicks. The match programme crinkles. The smell of grass and rain. Welcome to English football.',
      },
      {
        nodesAtMinLevel: 4,
        minLevel: 2,
        title: 'Battle-Hardened',
        description: 'Four nodes at level 2 or above. You know the league.',
        bonusLabel: '+20% XP in Premier League, unlock rivalry paths',
        lore: 'They say the Premier League has no easy games. After surviving relegation scraps and title races in the same week, you believe it.',
      },
      {
        nodesAtMinLevel: 5,
        minLevel: 3,
        title: 'League Master',
        description: 'All five nodes at maximum level. England bows.',
        bonusLabel: '+30% XP everywhere, exclusive "Three Lions" badge',
        lore: 'The final whistle blows at Wembley. Your name is known across every dressing room in England. The galaxy has a new English champion.',
      },
    ],
    nodes: [
      {
        id: 'pl-top4-race',
        regionId: 'premier-league',
        title: 'Top 4 Race',
        description: 'Study the points charts, goal differences, and form runs that define the battle for Champions League football.',
        type: 'challenge',
        maxLevel: 3,
        levelCosts: [100, 250, 500],
        levelRewards: [
          [{ type: 'xp', amount: 50, label: '50 XP' }],
          [{ type: 'xp', amount: 150, label: '150 XP' }, { type: 'lore', label: '"Top Four" lore entry' }],
          [{ type: 'xp', amount: 300, label: '300 XP' }, { type: 'badge', label: 'Champions League Dreamer badge' }],
        ],
        position: { col: 0, row: 0 },
      },
      {
        id: 'pl-title-showdown',
        regionId: 'premier-league',
        title: 'Title Showdown',
        description: 'Dive deep into the head-to-head records of the title contenders — past and present.',
        type: 'rivalry',
        maxLevel: 3,
        levelCosts: [150, 350, 700],
        levelRewards: [
          [{ type: 'xp', amount: 75, label: '75 XP' }],
          [{ type: 'xp', amount: 200, label: '200 XP' }, { type: 'lore', label: '"Champions" lore entry' }],
          [{ type: 'xp', amount: 400, label: '400 XP' }, { type: 'badge', label: 'Title Winner badge' }],
        ],
        position: { col: 2, row: 0 },
      },
      {
        id: 'pl-golden-boot',
        regionId: 'premier-league',
        title: 'Golden Boot Hunt',
        description: 'Analyse the top scorers race match by match and player by player.',
        type: 'legend',
        maxLevel: 3,
        levelCosts: [120, 300, 600],
        levelRewards: [
          [{ type: 'xp', amount: 60, label: '60 XP' }],
          [{ type: 'xp', amount: 180, label: '180 XP' }],
          [{ type: 'xp', amount: 350, label: '350 XP' }, { type: 'badge', label: 'Golden Boot badge' }],
        ],
        position: { col: 1, row: 1 },
      },
      {
        id: 'pl-relegation-zone',
        regionId: 'premier-league',
        title: 'Relegation Scrap',
        description: 'Survive the bottom three. Understand the math, the morale, the madness.',
        type: 'challenge',
        maxLevel: 3,
        levelCosts: [80, 200, 450],
        levelRewards: [
          [{ type: 'xp', amount: 40, label: '40 XP' }],
          [{ type: 'xp', amount: 120, label: '120 XP' }, { type: 'lore', label: '"Parachute" lore entry' }],
          [{ type: 'xp', amount: 280, label: '280 XP' }, { type: 'badge', label: 'Survivor badge' }],
        ],
        position: { col: 0, row: 2 },
      },
      {
        id: 'pl-classic-rivalries',
        regionId: 'premier-league',
        title: 'Classic Rivalries',
        description: 'The north-west derby, the north London derby, the Manchester clash. Study what makes them legendary.',
        type: 'rivalry',
        maxLevel: 3,
        levelCosts: [200, 500, 1000],
        levelRewards: [
          [{ type: 'xp', amount: 100, label: '100 XP' }],
          [{ type: 'xp', amount: 300, label: '300 XP' }, { type: 'lore', label: '"Derby Day" lore entry' }],
          [{ type: 'xp', amount: 600, label: '600 XP' }, { type: 'badge', label: 'Derby King badge' }],
        ],
        position: { col: 2, row: 2 },
      },
    ],
  },

  {
    id: 'la-liga',
    name: 'La Liga',
    country: 'Spain',
    color: '#003f8f',
    entryLore:
      'The sun beats down on the Bernabéu and Camp Nou. Two giants have cast shadows over Spanish football for decades — but new voices are rising. Girona, Athletic, the Basque firebrands. La Liga is not just El Clásico. It is an entire civilisation of football.',
    completionLore:
      'Spain\'s finest have nothing left to teach you. You have dissected every tiki-taka movement, every counter-press, every genius flick in the penalty area. The galaxy is richer for it.',
    milestones: [
      {
        nodesAtMinLevel: 2,
        minLevel: 1,
        title: 'Bienvenido a España',
        description: 'Two nodes unlocked in La Liga.',
        bonusLabel: '+10% XP in La Liga',
        lore: 'Mosaic tiles. White shirts. The click of a rondo passing drill under a cloudless sky.',
      },
      {
        nodesAtMinLevel: 4,
        minLevel: 2,
        title: 'El Estilo',
        description: 'Four nodes at level 2+.',
        bonusLabel: '+20% XP in La Liga, unlock Clásico paths',
      },
      {
        nodesAtMinLevel: 5,
        minLevel: 3,
        title: 'El Maestro',
        description: 'All nodes maxed. The galaxy\'s finest football mind.',
        bonusLabel: '+30% XP everywhere, "Maestro" title badge',
        lore: 'They write sonnets about the Spanish game. Now your name belongs in the same breath as the giants.',
      },
    ],
    nodes: [
      {
        id: 'll-clasico',
        regionId: 'la-liga',
        title: 'El Clásico',
        description: 'The most-watched club match on earth. Study its history, its drama, its defining moments.',
        type: 'rivalry',
        maxLevel: 3,
        levelCosts: [200, 500, 1000],
        levelRewards: [
          [{ type: 'xp', amount: 100, label: '100 XP' }],
          [{ type: 'xp', amount: 300, label: '300 XP' }],
          [{ type: 'xp', amount: 600, label: '600 XP' }, { type: 'badge', label: 'Clásico Veteran badge' }],
        ],
        position: { col: 1, row: 0 },
      },
      {
        id: 'll-tiki-taka',
        regionId: 'la-liga',
        title: 'Tiki-Taka Era',
        description: 'Possession, pressing, positional play. The tactical revolution that changed the world.',
        type: 'legend',
        maxLevel: 3,
        levelCosts: [150, 350, 700],
        levelRewards: [
          [{ type: 'xp', amount: 75, label: '75 XP' }],
          [{ type: 'xp', amount: 200, label: '200 XP' }, { type: 'lore', label: '"Possession" lore entry' }],
          [{ type: 'xp', amount: 400, label: '400 XP' }, { type: 'badge', label: 'Positional Play badge' }],
        ],
        position: { col: 0, row: 1 },
      },
      {
        id: 'll-golden-generation',
        regionId: 'la-liga',
        title: 'Golden Generation',
        description: 'Track the galácticos, the youth products, and the imports that defined an era.',
        type: 'legend',
        maxLevel: 3,
        levelCosts: [120, 300, 600],
        levelRewards: [
          [{ type: 'xp', amount: 60, label: '60 XP' }],
          [{ type: 'xp', amount: 180, label: '180 XP' }],
          [{ type: 'xp', amount: 350, label: '350 XP' }, { type: 'badge', label: 'Galáctico badge' }],
        ],
        position: { col: 2, row: 1 },
      },
      {
        id: 'll-atletico-wall',
        regionId: 'la-liga',
        title: 'The Defensive Wall',
        description: 'Atlético\'s block-and-counter mastery. The third giant that refuses to fall.',
        type: 'challenge',
        maxLevel: 3,
        levelCosts: [100, 250, 500],
        levelRewards: [
          [{ type: 'xp', amount: 50, label: '50 XP' }],
          [{ type: 'xp', amount: 150, label: '150 XP' }],
          [{ type: 'xp', amount: 300, label: '300 XP' }, { type: 'badge', label: 'The Wall badge' }],
        ],
        position: { col: 0, row: 2 },
      },
      {
        id: 'll-basque-pride',
        regionId: 'la-liga',
        title: 'Basque Pride',
        description: 'Athletic Bilbao and their cantera philosophy. Only local players, total identity.',
        type: 'team',
        maxLevel: 3,
        levelCosts: [130, 320, 650],
        levelRewards: [
          [{ type: 'xp', amount: 65, label: '65 XP' }],
          [{ type: 'xp', amount: 190, label: '190 XP' }, { type: 'lore', label: '"Cantera" lore entry' }],
          [{ type: 'xp', amount: 380, label: '380 XP' }, { type: 'badge', label: 'Euskadi badge' }],
        ],
        position: { col: 2, row: 2 },
      },
    ],
  },

  {
    id: 'bundesliga',
    name: 'Bundesliga',
    country: 'Germany',
    color: '#d3010c',
    entryLore:
      'The Bundesliga pulses with Gegenpressing energy. This is the league of standing sections, full-throated support, and clubs owned by their fans. The football here is fast, physical, and spectacularly direct.',
    completionLore:
      'You have earned the respect of every Kurve in Germany. The tifo that unfurls in your honour stretches from the Bayern block to the Yellow Wall of Dortmund.',
    milestones: [
      {
        nodesAtMinLevel: 2,
        minLevel: 1,
        title: 'Willkommen im Fußball',
        description: 'Two nodes unlocked in the Bundesliga.',
        bonusLabel: '+10% XP in Bundesliga',
        lore: 'Standing sections, beer in the stadium, and a Gegenpressing drill at 8 AM. Germany does football differently.',
      },
      {
        nodesAtMinLevel: 4,
        minLevel: 2,
        title: 'Das Pressing-Meister',
        description: 'Four nodes at level 2+.',
        bonusLabel: '+20% XP in Bundesliga, unlock Yellow Wall paths',
      },
      {
        nodesAtMinLevel: 5,
        minLevel: 3,
        title: 'Rekordmeister',
        description: 'All nodes maxed in the Bundesliga.',
        bonusLabel: '+30% XP everywhere, "Rekordmeister" badge',
        lore: 'The Meisterschale is yours — not on the pitch, but in the mind. Germany\'s football heritage runs through your veins.',
      },
    ],
    nodes: [
      {
        id: 'bl-yellow-wall',
        regionId: 'bundesliga',
        title: 'The Yellow Wall',
        description: 'Signal Iduna Park\'s Südtribüne — 25,000 standing supporters, the largest terrace in Europe.',
        type: 'legend',
        maxLevel: 3,
        levelCosts: [120, 300, 600],
        levelRewards: [
          [{ type: 'xp', amount: 60, label: '60 XP' }],
          [{ type: 'xp', amount: 180, label: '180 XP' }, { type: 'lore', label: '"Yellow Wall" lore entry' }],
          [{ type: 'xp', amount: 360, label: '360 XP' }, { type: 'badge', label: 'Südtribüne badge' }],
        ],
        position: { col: 0, row: 0 },
      },
      {
        id: 'bl-gegenpressing',
        regionId: 'bundesliga',
        title: 'Gegenpressing Bible',
        description: 'From Klopp\'s Dortmund to Tuchel\'s Bayern — the high-intensity press that remapped world football.',
        type: 'challenge',
        maxLevel: 3,
        levelCosts: [150, 380, 750],
        levelRewards: [
          [{ type: 'xp', amount: 75, label: '75 XP' }],
          [{ type: 'xp', amount: 225, label: '225 XP' }],
          [{ type: 'xp', amount: 450, label: '450 XP' }, { type: 'badge', label: 'Gegenpressing badge' }],
        ],
        position: { col: 2, row: 0 },
      },
      {
        id: 'bl-50plus1',
        regionId: 'bundesliga',
        title: '50+1 Rule',
        description: 'German clubs are majority-owned by their fans. Understand what this means for the soul of the game.',
        type: 'team',
        maxLevel: 3,
        levelCosts: [100, 250, 500],
        levelRewards: [
          [{ type: 'xp', amount: 50, label: '50 XP' }],
          [{ type: 'xp', amount: 150, label: '150 XP' }, { type: 'lore', label: '"Fan Ownership" lore entry' }],
          [{ type: 'xp', amount: 300, label: '300 XP' }, { type: 'badge', label: 'Die Fans badge' }],
        ],
        position: { col: 1, row: 1 },
      },
      {
        id: 'bl-wolf-pack',
        regionId: 'bundesliga',
        title: 'The Underdogs',
        description: 'Freiburg, Union Berlin, Heidenheim — clubs with tiny budgets punching above their weight.',
        type: 'challenge',
        maxLevel: 3,
        levelCosts: [90, 230, 460],
        levelRewards: [
          [{ type: 'xp', amount: 45, label: '45 XP' }],
          [{ type: 'xp', amount: 135, label: '135 XP' }],
          [{ type: 'xp', amount: 270, label: '270 XP' }, { type: 'badge', label: 'Underdog badge' }],
        ],
        position: { col: 0, row: 2 },
      },
      {
        id: 'bl-record-chaser',
        regionId: 'bundesliga',
        title: 'Bayern Supremacy',
        description: 'Ten consecutive league titles. Understand the machine, its glory, and the teams that try to stop it.',
        type: 'trophy',
        maxLevel: 3,
        levelCosts: [200, 500, 1000],
        levelRewards: [
          [{ type: 'xp', amount: 100, label: '100 XP' }],
          [{ type: 'xp', amount: 300, label: '300 XP' }],
          [{ type: 'xp', amount: 600, label: '600 XP' }, { type: 'badge', label: 'Meisterschale badge' }],
        ],
        position: { col: 2, row: 2 },
      },
    ],
  },

  {
    id: 'serie-a',
    name: 'Serie A',
    country: 'Italy',
    color: '#009246',
    entryLore:
      'Calcio is more than football. It is theatre, philosophy, and passion wrapped in a blue shirt and argued about over espresso. Serie A gave the world catenaccio, Mezzala, and football as art form.',
    completionLore:
      'You have mastered the tactical language of Calcio. Inter, Juventus, Napoli — each left their mark on your understanding. The galaxy speaks Italian now.',
    milestones: [
      {
        nodesAtMinLevel: 2,
        minLevel: 1,
        title: 'Benvenuti nel Calcio',
        description: 'Two nodes unlocked in Serie A.',
        bonusLabel: '+10% XP in Serie A',
        lore: 'The Curva erupts. The referee waves away the protests. A beautiful, chaotic theatre begins.',
      },
      {
        nodesAtMinLevel: 4,
        minLevel: 2,
        title: 'Il Professore',
        description: 'Four nodes at level 2+.',
        bonusLabel: '+20% XP in Serie A, unlock tactical deep-dives',
      },
      {
        nodesAtMinLevel: 5,
        minLevel: 3,
        title: 'Campione d\'Italia',
        description: 'All nodes maxed.',
        bonusLabel: '+30% XP everywhere, "Scudetto" badge',
        lore: 'The gold scudetto patch is sewn onto your shirt. Campione d\'Italia.',
      },
    ],
    nodes: [
      {
        id: 'sa-catenaccio',
        regionId: 'serie-a',
        title: 'Catenaccio Legacy',
        description: 'The Italian defensive system that shaped world football. Its evolution from a chain to a philosophy.',
        type: 'legend',
        maxLevel: 3,
        levelCosts: [120, 300, 600],
        levelRewards: [
          [{ type: 'xp', amount: 60, label: '60 XP' }],
          [{ type: 'xp', amount: 180, label: '180 XP' }, { type: 'lore', label: '"The Chain" lore entry' }],
          [{ type: 'xp', amount: 360, label: '360 XP' }, { type: 'badge', label: 'Catenaccio badge' }],
        ],
        position: { col: 0, row: 0 },
      },
      {
        id: 'sa-scudetto-race',
        regionId: 'serie-a',
        title: 'Scudetto Race',
        description: 'Follow the Italian title race — Inter, Juventus, Milan, Napoli — the eternal carousel.',
        type: 'challenge',
        maxLevel: 3,
        levelCosts: [150, 375, 750],
        levelRewards: [
          [{ type: 'xp', amount: 75, label: '75 XP' }],
          [{ type: 'xp', amount: 225, label: '225 XP' }],
          [{ type: 'xp', amount: 450, label: '450 XP' }, { type: 'badge', label: 'Scudetto Tracker badge' }],
        ],
        position: { col: 2, row: 0 },
      },
      {
        id: 'sa-derby-della-madonnina',
        regionId: 'serie-a',
        title: 'Derby della Madonnina',
        description: 'Inter vs AC Milan. The city of Milan divided by the colour of a shirt.',
        type: 'rivalry',
        maxLevel: 3,
        levelCosts: [180, 450, 900],
        levelRewards: [
          [{ type: 'xp', amount: 90, label: '90 XP' }],
          [{ type: 'xp', amount: 270, label: '270 XP' }, { type: 'lore', label: '"Madonnina" lore entry' }],
          [{ type: 'xp', amount: 540, label: '540 XP' }, { type: 'badge', label: 'Derby badge' }],
        ],
        position: { col: 1, row: 1 },
      },
      {
        id: 'sa-napoli-dream',
        regionId: 'serie-a',
        title: 'Napoli\'s Dream',
        description: 'The south rises. Napoli\'s scudetto after 33 years of waiting — the whole city in tears.',
        type: 'trophy',
        maxLevel: 3,
        levelCosts: [130, 320, 640],
        levelRewards: [
          [{ type: 'xp', amount: 65, label: '65 XP' }],
          [{ type: 'xp', amount: 195, label: '195 XP' }, { type: 'lore', label: '"Partenopei Dream" lore entry' }],
          [{ type: 'xp', amount: 390, label: '390 XP' }, { type: 'badge', label: 'Napoli 33 badge' }],
        ],
        position: { col: 0, row: 2 },
      },
      {
        id: 'sa-atalanta-rise',
        regionId: 'serie-a',
        title: 'Atalanta\'s Rise',
        description: 'From mid-table obscurity to Champions League nights. The Gasperini revolution.',
        type: 'team',
        maxLevel: 3,
        levelCosts: [100, 250, 500],
        levelRewards: [
          [{ type: 'xp', amount: 50, label: '50 XP' }],
          [{ type: 'xp', amount: 150, label: '150 XP' }],
          [{ type: 'xp', amount: 300, label: '300 XP' }, { type: 'badge', label: 'La Dea badge' }],
        ],
        position: { col: 2, row: 2 },
      },
    ],
  },

  {
    id: 'ligue-1',
    name: 'Ligue 1',
    country: 'France',
    color: '#091c3e',
    entryLore:
      'Paris is a galaxy unto itself. But beyond the capital, Marseille burns with the white-hot passion of the Vélodrome, Monaco glitters, and Lyon quietly builds the next generation of French talent. Ligue 1 is underestimated — always.',
    completionLore:
      'Liberté, Égalité, Ballon. France\'s football culture is yours now. From the academies of Clairefontaine to the Parc des Princes, you have seen it all.',
    milestones: [
      {
        nodesAtMinLevel: 2,
        minLevel: 1,
        title: 'Bienvenue en France',
        description: 'Two nodes unlocked in Ligue 1.',
        bonusLabel: '+10% XP in Ligue 1',
        lore: 'The baguette is optional. The football passion is not. Ligue 1 welcomes you.',
      },
      {
        nodesAtMinLevel: 4,
        minLevel: 2,
        title: 'Le Créatif',
        description: 'Four nodes at level 2+.',
        bonusLabel: '+20% XP in Ligue 1, unlock Paris rivalry paths',
      },
      {
        nodesAtMinLevel: 5,
        minLevel: 3,
        title: 'Champion de France',
        description: 'All nodes maxed.',
        bonusLabel: '+30% XP everywhere, "Tricolore" badge',
        lore: 'The tricolore waves from every window. France has found its champion.',
      },
    ],
    nodes: [
      {
        id: 'l1-psg-empire',
        regionId: 'ligue-1',
        title: 'PSG Empire',
        description: 'Qatar money, world-class signings, and the pursuit of the Champions League. The project that rewrote French football.',
        type: 'team',
        maxLevel: 3,
        levelCosts: [180, 450, 900],
        levelRewards: [
          [{ type: 'xp', amount: 90, label: '90 XP' }],
          [{ type: 'xp', amount: 270, label: '270 XP' }],
          [{ type: 'xp', amount: 540, label: '540 XP' }, { type: 'badge', label: 'Ici c\'est Paris badge' }],
        ],
        position: { col: 1, row: 0 },
      },
      {
        id: 'l1-marseille-passion',
        regionId: 'ligue-1',
        title: 'Marseille Passion',
        description: 'The Vélodrome at full roar. OM vs PSG — the match that stops France.',
        type: 'rivalry',
        maxLevel: 3,
        levelCosts: [150, 375, 750],
        levelRewards: [
          [{ type: 'xp', amount: 75, label: '75 XP' }],
          [{ type: 'xp', amount: 225, label: '225 XP' }, { type: 'lore', label: '"Le Classique" lore entry' }],
          [{ type: 'xp', amount: 450, label: '450 XP' }, { type: 'badge', label: 'Le Classique badge' }],
        ],
        position: { col: 0, row: 1 },
      },
      {
        id: 'l1-academies',
        regionId: 'ligue-1',
        title: 'French Academies',
        description: 'Clairefontaine and the INF pipeline. France produces more professional footballers than any country on earth.',
        type: 'legend',
        maxLevel: 3,
        levelCosts: [120, 300, 600],
        levelRewards: [
          [{ type: 'xp', amount: 60, label: '60 XP' }],
          [{ type: 'xp', amount: 180, label: '180 XP' }, { type: 'lore', label: '"Clairefontaine" lore entry' }],
          [{ type: 'xp', amount: 360, label: '360 XP' }, { type: 'badge', label: 'Academy Master badge' }],
        ],
        position: { col: 2, row: 1 },
      },
      {
        id: 'l1-monaco-glamour',
        regionId: 'ligue-1',
        title: 'Monaco Glamour',
        description: 'Princes, yachts, and impossible Champions League nights. The most romantic club in European football?',
        type: 'team',
        maxLevel: 3,
        levelCosts: [130, 325, 650],
        levelRewards: [
          [{ type: 'xp', amount: 65, label: '65 XP' }],
          [{ type: 'xp', amount: 195, label: '195 XP' }],
          [{ type: 'xp', amount: 390, label: '390 XP' }, { type: 'badge', label: 'Principality badge' }],
        ],
        position: { col: 0, row: 2 },
      },
      {
        id: 'l1-next-gen',
        regionId: 'ligue-1',
        title: 'Next Generation',
        description: 'Mbappé came from here. Benzema\'s roots are here. Who is next to emerge from French soil?',
        type: 'challenge',
        maxLevel: 3,
        levelCosts: [140, 350, 700],
        levelRewards: [
          [{ type: 'xp', amount: 70, label: '70 XP' }],
          [{ type: 'xp', amount: 210, label: '210 XP' }, { type: 'lore', label: '"Les Bleus Factory" lore entry' }],
          [{ type: 'xp', amount: 420, label: '420 XP' }, { type: 'badge', label: 'Pépite badge' }],
        ],
        position: { col: 2, row: 2 },
      },
    ],
  },
]

export function getRegion(id: string): Region | undefined {
  return GALAXY_REGIONS.find((r) => r.id === id)
}

export function getNode(nodeId: string): { region: Region; node: Region['nodes'][0] } | undefined {
  for (const region of GALAXY_REGIONS) {
    const node = region.nodes.find((n) => n.id === nodeId)
    if (node) return { region, node }
  }
  return undefined
}
